### ISSUE TITLE
[Feat] 게시판 피드에 n일차 글인지 알 수 있다.

### ISSUE THREAD

**Issue by chkim116** [BumgeunSong/daily-writing-friends#22]
- 오늘 게시한 글이 n일차 글인지 표시함. or n일마다 구분선이 지어져서 2일차, 3일차로 구분 표기.

**Comment by chkim116** [comment]
@BumgeunSong 범근님 요 아이디어 어때요?
만약 n일차 표시하려면, 매글프 6기(board라고 하나욤?)의 시작과 종료 시점을 DB에 저장해놔야할듯합니당.

**Comment by chkim116** [comment]
아니면, 게시글 목록 검색/필터링 추가해버리는거도 방법일듯

**Comment by BumgeunSong** [comment]
@chkim116 창회님 
- 피드에서 글쓴이 필터링 기능 지금 작업 중인데, 곧 올릴게요! 이 필터가 있으면 각 사람마다 글을 나눠볼 수 있어요.
- N일차는 요렇게 추가하면 어떨까 싶어요.

- Firestore 'boards' collection에 startDate를 추가
- startDate로 부터 'post.createdAt'이 몇일 차인지 글 작성 시에 저장 (나중에 fetch하는 것보다 작성 시점에 저장하는 게 나을 듯?)

UI 표시
> 작성자: kyungsuk jeon | 작성일: 11/16/2024, 12:58:18 PM **· N일차**

**Comment by chkim116** [comment]
@BumgeunSong 좋은거같아여! 👍

**Comment by chkim116** [comment]
![image](https://github.com/user-attachments/assets/3707180d-2125-4d14-b71c-3ed982eecb3a)

이런 간단한건 어떄요?
